[project]
name = "kebab-gui"
version = "1.0.0"
description = "A high-performance, window-based operating system"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    {name = "James", username = "@7aimez"}
]
dependencies = [
    "pygame",
    "requests",
    "html2image"
]
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
